language: ruby
script:   bundle exec rake
cache:    bundler
sudo:     false

before_install:
  - gem install bundler

after_success:
  - bundle exec rake test:accuracy
  - bundle exec rake benchmark:memory

rvm:
  - 2.3.1
  - ruby-head
  - jruby-9.1.6.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-9.1.6.0
    - rvm: jruby-head
